# Generated by Django 5.2.1 on 2025-05-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('job_industry', models.CharField(choices=[('IT', 'Information Technology'), ('FIN', 'Finance'), ('EDU', 'Education'), ('MKT', 'Marketing'), ('OTH', 'Other')], max_length=50)),
                ('job_type', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('IN', 'Internship'), ('CT', 'Contract')], max_length=50)),
                ('job_title', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('company_overview', models.TextField()),
                ('eligible_courses', models.CharField(max_length=255)),
                ('eligibility_criteria', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('ctc', models.CharField(max_length=50)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
