# Generated by Django 5.2.1 on 2025-05-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
